// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedAllOpenModelIT : org.jetbrains.kotlin.gradle.model.AllOpenModelIT() {
    override val advanceGradleVersion = true
}
