// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedMultiplatformGradleIT : org.jetbrains.kotlin.gradle.MultiplatformGradleIT() {
    override val advanceGradleVersion = true
}
