// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedNoArgModelIT : org.jetbrains.kotlin.gradle.model.NoArgModelIT() {
    override val advanceGradleVersion = true
}
