// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKaptIncrementalWithAggregatingApt : org.jetbrains.kotlin.gradle.KaptIncrementalWithAggregatingApt() {
    override val advanceGradleVersion = true
}
