// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKotlinAndroidExtensionIT : org.jetbrains.kotlin.gradle.model.KotlinAndroidExtensionIT() {
    override val advanceGradleVersion = true
}
