// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedHierarchicalMppIT : org.jetbrains.kotlin.gradle.HierarchicalMppIT() {
    override val advanceGradleVersion = true
}
