// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedSamWithReceiverModelIT : org.jetbrains.kotlin.gradle.model.SamWithReceiverModelIT() {
    override val advanceGradleVersion = true
}
