// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKotlinAndroid32GradleIT : org.jetbrains.kotlin.gradle.KotlinAndroid32GradleIT() {
    override val advanceGradleVersion = true
}
