// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKapt3WorkersAndroid32IT : org.jetbrains.kotlin.gradle.Kapt3WorkersAndroid32IT() {
    override val advanceGradleVersion = true
}
