// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKapt3Android33IT : org.jetbrains.kotlin.gradle.Kapt3Android33IT() {
    override val advanceGradleVersion = true
}
