// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedVariantAwareDependenciesIT : org.jetbrains.kotlin.gradle.VariantAwareDependenciesIT() {
    override val advanceGradleVersion = true
}
