// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKapt3Android31IT : org.jetbrains.kotlin.gradle.Kapt3Android31IT() {
    override val advanceGradleVersion = true
}
