// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKaptModelIT : org.jetbrains.kotlin.gradle.model.KaptModelIT() {
    override val advanceGradleVersion = true
}
