// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKotlin2JsGradlePluginIT : org.jetbrains.kotlin.gradle.Kotlin2JsGradlePluginIT() {
    override val advanceGradleVersion = true
}
