// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedNewMultiplatformIT : org.jetbrains.kotlin.gradle.NewMultiplatformIT() {
    override val advanceGradleVersion = true
}
