// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKapt3WorkersIT : org.jetbrains.kotlin.gradle.Kapt3WorkersIT() {
    override val advanceGradleVersion = true
}
