// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedIncrementalJavaChangePreciseIT : org.jetbrains.kotlin.gradle.IncrementalJavaChangePreciseIT() {
    override val advanceGradleVersion = true
}
