// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKotlinAndroid33GradleIT : org.jetbrains.kotlin.gradle.KotlinAndroid33GradleIT() {
    override val advanceGradleVersion = true
}
