// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedIncrementalCompilationJsMultiProjectIT : org.jetbrains.kotlin.gradle.IncrementalCompilationJsMultiProjectIT() {
    override val advanceGradleVersion = true
}
