// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedJavaUpToDateIT : org.jetbrains.kotlin.gradle.JavaUpToDateIT() {
    override val advanceGradleVersion = true
}
