// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKotlinDaemonIT : org.jetbrains.kotlin.gradle.KotlinDaemonIT() {
    override val advanceGradleVersion = true
}
