// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedBuildCacheIT : org.jetbrains.kotlin.gradle.BuildCacheIT() {
    override val advanceGradleVersion = true
}
