// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedSimpleKotlinGradleIT : org.jetbrains.kotlin.gradle.SimpleKotlinGradleIT() {
    override val advanceGradleVersion = true
}
