// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedGradleDaemonMemoryIT : org.jetbrains.kotlin.gradle.GradleDaemonMemoryIT() {
    override val advanceGradleVersion = true
}
