// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKaptIncrementalIT : org.jetbrains.kotlin.gradle.KaptIncrementalIT() {
    override val advanceGradleVersion = true
}
