// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKaptIncrementalWithIsolatingApt : org.jetbrains.kotlin.gradle.KaptIncrementalWithIsolatingApt() {
    override val advanceGradleVersion = true
}
