// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedIncrementalJavaChangeDefaultIT : org.jetbrains.kotlin.gradle.IncrementalJavaChangeDefaultIT() {
    override val advanceGradleVersion = true
}
