// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedIncrementalJavaChangeDisablePreciseIT : org.jetbrains.kotlin.gradle.IncrementalJavaChangeDisablePreciseIT() {
    override val advanceGradleVersion = true
}
