// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedTestRootAffectedIT : org.jetbrains.kotlin.gradle.TestRootAffectedIT() {
    override val advanceGradleVersion = true
}
