// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedExecutionStrategyJvmIT : org.jetbrains.kotlin.gradle.ExecutionStrategyJvmIT() {
    override val advanceGradleVersion = true
}
