// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKotlinGradleIT : org.jetbrains.kotlin.gradle.KotlinGradleIT() {
    override val advanceGradleVersion = true
}
