// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedCoroutinesIT : org.jetbrains.kotlin.gradle.CoroutinesIT() {
    override val advanceGradleVersion = true
}
