// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedPluginsDslIT : org.jetbrains.kotlin.gradle.PluginsDslIT() {
    override val advanceGradleVersion = true
}
