// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedBuildCacheRelocationIT : org.jetbrains.kotlin.gradle.BuildCacheRelocationIT() {
    override val advanceGradleVersion = true
}
