// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedWorkersIT : org.jetbrains.kotlin.gradle.WorkersIT() {
    override val advanceGradleVersion = true
}
