// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKotlinAndroid30GradleIT : org.jetbrains.kotlin.gradle.KotlinAndroid30GradleIT() {
    override val advanceGradleVersion = true
}
