// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedClassFileIsRemovedIT : org.jetbrains.kotlin.gradle.ClassFileIsRemovedIT() {
    override val advanceGradleVersion = true
}
