// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedCocoaPodsIT : org.jetbrains.kotlin.gradle.CocoaPodsIT() {
    override val advanceGradleVersion = true
}
