// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedUpToDateIT : org.jetbrains.kotlin.gradle.UpToDateIT() {
    override val advanceGradleVersion = true
}
