// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedExecutionStrategyJsIT : org.jetbrains.kotlin.gradle.ExecutionStrategyJsIT() {
    override val advanceGradleVersion = true
}
