// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKapt3IT : org.jetbrains.kotlin.gradle.Kapt3IT() {
    override val advanceGradleVersion = true
}
