// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKotlinProjectIT : org.jetbrains.kotlin.gradle.model.KotlinProjectIT() {
    override val advanceGradleVersion = true
}
