// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedKapt3Android32IT : org.jetbrains.kotlin.gradle.Kapt3Android32IT() {
    override val advanceGradleVersion = true
}
