// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedConfigurationAvoidanceIT : org.jetbrains.kotlin.gradle.ConfigurationAvoidanceIT() {
    override val advanceGradleVersion = true
}
