// DO NOT EDIT MANUALLY! GENERATED BY generateTestsWithAdvancedVersion.kt
package org.jetbrains.kotlin.gradle.advanced

class AdvancedIncrementalCompilationJvmMultiProjectIT : org.jetbrains.kotlin.gradle.IncrementalCompilationJvmMultiProjectIT() {
    override val advanceGradleVersion = true
}
